### ISSUE TITLE
iPad issue on Route Details

### ISSUE THREAD

**Issue by MikeLutgeMG** [whatcomtrans/WTA.Scheduler#17]
The iPad seems to have a problem with this line of js:var columnId = parseInt($('#stopNames td:nth-child(' + (k + 1) + ')').attr('id'));
It is coming back as undefined except for the first column. The result is that only the first column contains stop times on an iPad.

**Comment by andymwta** [comment]
Also on iPhone 5c

**Comment by andymwta** [comment]
Working fine on a MacBook with OS X 10.9.5 Safari.

**Comment by andymwta** [comment]
Got it!
