### ISSUE TITLE
Note for Days Without Trips

### ISSUE THREAD

**Issue by joshn-ridewta-com** [whatcomtrans/WTA.Scheduler#19]
We need a generic "note" displayed in place of the route schedule on days when there are no trips scheduled.  This could be because of WWU schedule, Saturday or Sunday service.  Basically something that indicates, no, I am not broken, there are just no trips scheduled.  Recommended language:  "This route does not have any trips scheduled for the selected day."

**Comment by andymwta** [comment]
Done. "There is no service for the specified route and time."
