### ISSUE TITLE
Do Not Show Arrival Time on Stops List

### ISSUE THREAD

**Issue by joshn-ridewta-com** [whatcomtrans/WTA.Scheduler#21]
For all stops, do not show arrival time (drop off only) on the stops list.  The stops times have drop off or arrival only indicators.

**Comment by andymwta** [comment]
Added condition to conditional statement that removes any stop time at which passengers cannot board. Waiting on a new GTFS export and data upload to see the results of this. Marking it closed since the code is minimal.
