### ISSUE TITLE
Indicate Arrival Only Stops in Route Display

### ISSUE THREAD

**Issue by joshn-ridewta-com** [whatcomtrans/WTA.Scheduler#22]
On the route display, for pickup vs drop off, show both stops.  Mark the stop with drop off only indicated as "(arrival)".

**Comment by joshn-ridewta-com** [comment]
Latest export now includes pickuptype=1.  When pickuptype is "1" and mark as arrival.  Still need to update UI to display "arrival".

**Comment by andymwta** [comment]
After reviewing the code, I already have it filtering out stop times that passengers cannot board at.
