### ISSUE TITLE
Implement Load Time Optimizations

### ISSUE THREAD

**Issue by joshn-ridewta-com** [whatcomtrans/WTA.Scheduler#26]

**Comment by joshn-ridewta-com** [comment]
The only load time optimization we will focus on for go live is gzip compression of the data.

**Comment by andymwta** [comment]
Looks like after gzipping data_trips, the biggest hinderance is jquery.min.js and schedules.min.js.
We can look at serving gzipped versions of these as well.

Other thoughts, we have 46 requests. If we can reduce this number it will help.

**Comment by joshn-ridewta-com** [comment]
The biggest challenge right now with the gzip is the client side detention which messes with load order.  But I agree.  I would like to move to using gzip of the css, js and data_routes.

I just minified the JS so keep that in mind if you make updates to any of the JS and updated the app cache.  This should speed things up some.

Need  a better framework though for loading the other scripts…

R. Josh Nylander
Director of IT
Whatcom Transportation Authority
4111 Bakerview Spur Road
Bellingham, WA  98226
p: 360-788-9341 / f: 360-788-9541
joshn@ridewta.commailto:joshn@ridewta.com

E-mail to and from this address may be subject to public disclosure under Washington’s Public Records Act.
