### ISSUE TITLE
Re-work the maps page for better mobile support

### ISSUE THREAD

**Issue by joshn-ridewta-com** [whatcomtrans/WTA.Scheduler#27]

**Comment by andymwta** [comment]
To test after main site is linked to scheduling app properly. Made a couple of tweaks in an earlier push to add responsive nature to the map. Will need a variety of devices to test this as browser emulators do not accurately show behavior on native devices.

**Comment by andymwta** [comment]
Add media query to keep right bar from crowding map

**Comment by andymwta** [comment]
Do we want to have a fullscreen option?
It's somewhat difficult to use an embedded map on a phone that isn't full screen.
If so these css changes will do it:
.map-container {position: inherit}
#map-canvas {margin-top:0}

**Comment by andymwta** [comment]
Only issue left is when phones go to landscape mode.
Map takes up 99% of the screen making it very difficult to scroll up/down the page.
Need to write a media query for orientation and change the max-height property.
