### ISSUE TITLE
Spanish Version

### ISSUE THREAD

**Issue by joshn-ridewta-com** [whatcomtrans/WTA.Scheduler#34]
Need to setup to support other languages, specifically Spanish.

**Comment by joshn-ridewta-com** [comment]
Site horarios.ridewta.com is setup in S3 expecting an index page of "schedules-es.html".  Note, all links within site should us "/" instead of "/schedules.html".

**Comment by joshn-ridewta-com** [comment]
Cleaned up links to schedules.html

**Comment by joshn-ridewta-com** [comment]
Created a new variable, language, which will currently either have the value "en" for English or "es" for Spanish.  The variable is set globally on the new schedules-en.html and schedules-es.html.

**Comment by joshn-ridewta-com** [comment]
Created supfolders en and es under common folder.

**Comment by joshn-ridewta-com** [comment]
schedules.ridewta.com and testschedules.ridewta.com changed to use schedules-en.html as the "index" page.

**Comment by joshn-ridewta-com** [comment]
Still need to setup a function for messages within main.js and translate the content from common\es

**Comment by joshn-ridewta-com** [comment]
Added language query parameter to the google maps script tag in both schedules files as appropriate.

**Comment by joshn-ridewta-com** [comment]
Updated main.js to use a new function called "lang".  It wraps all of the words and phrases and returns the spanish version if the language variable is set to es.  It uses two simple arrays (see bottom of main.js).  I used Google Translate to translate all of the phrases.  Created a word document with the words and phrases to send for official translation.  There is one complex phrase that may need more then simple lang treatment.

**Comment by joshn-ridewta-com** [comment]
Translation of common files not completed.  Sending list of words and phrases to translation service.

**Comment by andymwta** [comment]
Navigation menu on horarios.ridewta.com needs to be updated with Spanish terms.

**Comment by joshn-ridewta-com** [comment]
Nav menu updated.

**Comment by joshn-ridewta-com** [comment]
Need to update jquery-ui.region
