### ISSUE TITLE
GTFS Pre-Processing Scripts

### ISSUE THREAD

**Issue by joshn-ridewta-com** [whatcomtrans/WTA.Scheduler#35]
Need to write/update the GTFS pre-processing scripts and integrate into code set.

**Comment by joshn-ridewta-com** [comment]
Also see Skagit trips issue.

**Comment by andymwta** [comment]
Testing output data from this now

**Comment by andymwta** [comment]
Data appears to be correct. Awaiting further testing from Dori and finalization of SQL export scripts but data is good to go until next signup which should come out around the new year. Removing launch blocking tag.

**Comment by andymwta** [comment]
Working on combining SQL query into one ps1 file.
