### ISSUE TITLE
AppCache Error on data_trips.js

### ISSUE THREAD

**Issue by andymwta** [whatcomtrans/WTA.Scheduler#50]
Application Cache Error event: Resource fetch failed (404) http://data.ridewta.com/gfts/website/data_trips.js

Not sure why this is happening, it looks correct in wta.appcache?
This seems to be hanging up the app indefinitely on some occasions, not sure of the full impact.

**Comment by andymwta** [comment]
I'm not sure on this one- We have copies of data_trips.js at both http://data.ridewta.com/gtfs/website/data_trips.js and http://data.ridewta.com/gtfs/data_trips.js

Either one should be valid but that is 100% of the time causing an App Cache error that frequently will totally hang up the application.

Any thoughts?

**Comment by joshn-ridewta-com** [comment]
Not seeing error in IE.  Need to watch and make sure this clears up.

**Comment by joshn-ridewta-com** [comment]
No longer seeing it in Chrome either.

**Comment by andymwta** [comment]
I still get this every time.
It doesn't seem to impact performance much now that the data files are being served as .gz though

**Comment by joshn-ridewta-com** [comment]
Sorry, still cannot reproduce when using incognito mode.  Do you need to try clearing your cache?

R. Josh Nylander
Director of IT
Whatcom Transportation Authority
4111 Bakerview Spur Road
Bellingham, WA  98226
p: 360-788-9341 / f: 360-788-9541
joshn@ridewta.commailto:joshn@ridewta.com

E-mail to and from this address may be subject to public disclosure under Washington’s Public Records Act.
