### ISSUE TITLE
Trip Planner on SharePoint side issues

### ISSUE THREAD

**Issue by andymwta** [whatcomtrans/WTA.Scheduler#53]
Producing incorrect information and inconsistent with trip planner on scheduling app side.

To reproduce:
Use Trip Planner at test.ridewta.com
start loc: 887 St Andrews Way
end loc: Dirty Dans
Date: tomorrow (8/18/2015)
Time: 7:00 AM
Departing

The route produced has the user walk 2 miles to a station and catch a bus that doesn't run at that time.
Then it has the user wait until the next morning (7 hours) at the bus station and catch the bus to Dirty Dans.

When doing the same on the Trip Planner from the Scheduling App, correct directions are produced.

The only differences in the two that I can see is that the Trip Planner in test.ridewta.com is not within a form element and data is being sent through a javascript instead of a form action.

**Comment by MikeLutgeMG** [comment]
Due to jquery not picking up correct value for departing or arriving.
