### ISSUE TITLE
Modify data load scripts to use GZIP

### ISSUE THREAD

**Issue by joshn-ridewta-com** [whatcomtrans/WTA.Scheduler#63]
Modify the data load scripts to check for the Accept-Encoding: gzip header and so load the [filename].gz

**Comment by joshn-ridewta-com** [comment]
Once I have the gzipped content, I can use this method to setup support for it.
http://blog.kenweiner.com/2009/08/serving-gzipped-javascript-files-from.html

**Comment by andymwta** [comment]
I've gzipped the two data files and placed them up on S3.

bash shell command:
gzip -cr9 <path to directory>

**Comment by joshn-ridewta-com** [comment]
Setup use of gzip for "data_trips.js.gz".  Need to refactor to also use the data_routes.  But good enough for go live.
