### ISSUE TITLE
Bad Stops.kml reference in mapping

### ISSUE THREAD

**Issue by joshn-ridewta-com** [whatcomtrans/WTA.Scheduler#64]
Found a reference to a KML file from the old site in main.js:
url: 'http://www.ridewta.com/files/file/maps/2015/Stops.kml',

**Comment by andymwta** [comment]
The reference is working but we should probably serve kml files from the data bucket on S3. I'll move it over there.

**Comment by andymwta** [comment]
Moved to data.ridewta.com/kml/stops.kml
