### ISSUE TITLE
scheduling app does not fire displayselectedroutes() when going to hash page

### ISSUE THREAD

**Issue by andymwta** [whatcomtrans/WTA.Scheduler#66]
When going to a page with a hashed variable, displaySelectedRoutes() is not fired and the spinner then indefinitely spins.

**Comment by andymwta** [comment]
Easiest to reproduce by going to a page such as:

http://schedules.ridewta.com/#route-details?routeId=1431

and refreshing the page. You should notice the spinner indefinitely spinning. If you open the console and type "displaySelectedroute()" the page will render. Something to do with recent code changes.

**Comment by joshn-ridewta-com** [comment]
OK, I will take a look tonight.

R. Josh Nylander
Director of IT, WTA
(360) 788-9341

On Aug 24, 2015 12:13 PM, AndyM notifications@github.com wrote:

Assigned #66https://github.com/whatcomtrans/WTA.Scheduler/issues/66 to @joshn-ridewta-comhttps://github.com/joshn-ridewta-com.

**Comment by andymwta** [comment]
Mike fixed this.
