### ISSUE TITLE
Majority of stops do not render on stops page

### ISSUE THREAD

**Issue by andymwta** [whatcomtrans/WTA.Scheduler#67]
Some recent code changes have broken the stops page.
Cannot read property 'route_id' of undefined.
Line 1444

**Comment by joshn-ridewta-com** [comment]
Also finding that on some stops pages the "routes" do not populate.

**Comment by andymwta** [comment]
This was a problem with the SQL query that produced the trips variable from trapeze data.
Corrected and uploaded new data.
