### ISSUE TITLE
Links to scheduling app routes/stops break on new signup

### ISSUE THREAD

**Issue by andymwta** [whatcomtrans/WTA.Scheduler#71]
Due to the fact that trapeze changes the route and stop ids every signup, any hard coded links from the sharepoint site to those specific route or stop pages will break when a new set of data is released.

Need to address this before the next signup (probably around new year)

Change to use stop code instead of stop id is probably the easiest way to go about fixing the stops half of the problem. Change to using route short name for routes?

**Comment by joshn-ridewta-com** [comment]
I added support for route name/number a while back but we probably need to test a bit further and then update SharePoint links.

R. Josh Nylander
Director of IT
Whatcom Transportation Authority
4111 Bakerview Spur Road
Bellingham, WA  98226
p: 360-788-9341 / f: 360-788-9541
joshn@ridewta.commailto:joshn@ridewta.com

E-mail to and from this address may be subject to public disclosure under Washington’s Public Records Act.

**Comment by andymwta** [comment]
Tiffany has updated the links on the sharepoint site. Should be good to go.
