### ISSUE TITLE
Browser page freezes on some devices (iPad mostly)

### ISSUE THREAD

**Issue by joshn-ridewta-com** [whatcomtrans/WTA.Scheduler#73]
When browsing on iPad the links on the home page to different route details do not respond to touch.

**Comment by joshn-ridewta-com** [comment]
I will bring in an iPad mini for testing.  Note this is in Safari.

Further research shows that the URL changes but the page does not load.  If I refresh then loads.

Oh wait, it did finally load on it's own but the user has no indication it is trying to load.

**Comment by andymwta** [comment]
Everything seems to work, I've noticed that on my iPad on initial site load the browser froze for a few seconds which is probably due to upfront processing demands. Maybe we can reduce this load?

**Comment by andymwta** [comment]
Removed appcache double check function from schedules.html- this should help with the freezing issue. Might still want to look into this more though.
