### ISSUE TITLE
Convert map images to sprite

### ISSUE THREAD

**Issue by joshn-ridewta-com** [whatcomtrans/WTA.Scheduler#74]

**Comment by andymwta** [comment]
Uploaded new map images for go live.
Work on sprite post go live.

**Comment by andymwta** [comment]
Actually, looking at how we populate the route image, using a sprite for this would seriously hinder performance unless we load the route maps sprite up front.

Currently we are only calling these images once the user goes to the route-details page for a specific route and the images are only 500Kb or less. A full sprite of all routes would be 15.5Kb. If we load the sprite on app load, it's worth it. If not, we should stick to individual images.

Do we want to sprite any other images?
